export const REGISTRATION_PAGE = 'totoro-web-registrationPage/';

export const GET_REGISTRATIONS_START = `${REGISTRATION_PAGE}GET_REGISTRATIONS_START`;

export const GET_REGISTRATIONS_SUCCESS = `${REGISTRATION_PAGE}GET_REGISTRATIONS_SUCCESS`;

export const SET_SELECTED_DATE_SUCCESS = `${REGISTRATION_PAGE}SET_SELECTED_DATE_SUCCESS`;
