export const REGISTRATION_PAGE = 'totoro-web-registrationPage/';

export const GET_REGISTRATIONS_START = `${REGISTRATION_PAGE}GET_REGISTRATIONS_START`;

export const GET_REGISTRATIONS_SUCCESS = `${REGISTRATION_PAGE}GET_REGISTRATIONS_SUCCESS`;

export const SET_SELECTED_DATE_SUCCESS = `${REGISTRATION_PAGE}SET_SELECTED_DATE_SUCCESS`;

export const CHANGE_DRAWER_VISIBLE = `${REGISTRATION_PAGE}CHANGE_DRAWER_VISIBLE`;

export const ON_SELECT_PATIENT = `${REGISTRATION_PAGE}ON_SELECT_PATIENT`;

export const GET_DOC_START = `${REGISTRATION_PAGE}GET_DOC_START`;

export const GET_DOC_SUCCESS = `${REGISTRATION_PAGE}GET_DOC_SUCCESS`;
