export const REGISTRATION_PAGE = 'totoro-web-registrationPage/';

export const GET_REGISTRATIONS_START = `${REGISTRATION_PAGE}GET_REGISTRATIONS_START`;

export const GET_REGISTRATIONS_SUCCESS = `${REGISTRATION_PAGE}GET_REGISTRATIONS_SUCCESS`;

export const SET_SELECTED_DATE_SUCCESS = `${REGISTRATION_PAGE}SET_SELECTED_DATE_SUCCESS`;

export const CHANGE_DRAWER_VISIBLE = `${REGISTRATION_PAGE}CHANGE_DRAWER_VISIBLE`;

export const ON_SELECT_PATIENT = `${REGISTRATION_PAGE}ON_SELECT_PATIENT`;

export const GET_DOC_START = `${REGISTRATION_PAGE}GET_DOC_START`;

export const GET_DOC_SUCCESS = `${REGISTRATION_PAGE}GET_DOC_SUCCESS`;

export const OPEN_XRAY = `${REGISTRATION_PAGE}OPEN_XRAY`;

export const XRAY_GREETING = `${REGISTRATION_PAGE}XRAY_GREETING`;

export const XRAY_GREETING_SUCCESS = `${REGISTRATION_PAGE}XRAY_GREETING_SUCCESS`;

export const XRAY_GREETING_FAILURE = `${REGISTRATION_PAGE}XRAY_GREETING_FAILURE`;

export const ON_LEAVE_PAGE = `${REGISTRATION_PAGE}ON_LEAVE_PAGE`;
