export const NHI_INDEX_PAGE = 'totoro-web-nhiIndexPage/';

export const GET_OD_INDEXES = `${NHI_INDEX_PAGE}GET_OD_INDEXES`;

export const GET_OD_INDEXES_SUCCESS = `${NHI_INDEX_PAGE}GET_OD_INDEXES_SUCCESS`;

export const GET_OD_INDEXES_FAIL = `${NHI_INDEX_PAGE}GET_OD_INDEXES_FAIL`;

export const GET_DOCTOR_NHI_EXAM = `${NHI_INDEX_PAGE}GET_DOCTOR_NHI_EXAM`;

export const GET_DOCTOR_NHI_EXAM_SUCCESS = `${NHI_INDEX_PAGE}GET_DOCTOR_NHI_EXAM_SUCCESS`;

export const GET_DOCTOR_NHI_EXAM_FAIL = `${NHI_INDEX_PAGE}GET_DOCTOR_NHI_EXAM_FAIL`;

export const GET_DOCTOR_NHI_TX = `${NHI_INDEX_PAGE}GET_DOCTOR_NHI_TX`;

export const GET_DOCTOR_NHI_TX_SUCCESS = `${NHI_INDEX_PAGE}GET_DOCTOR_NHI_TX_SUCCESS`;

export const GET_DOCTOR_NHI_TX_FAIL = `${NHI_INDEX_PAGE}GET_DOCTOR_NHI_TX_FAIL`;

export const GET_TOOTH_CLEAN = `${NHI_INDEX_PAGE}GET_TOOTH_CLEAN`;

export const GET_TOOTH_CLEAN_SUCCESS = `${NHI_INDEX_PAGE}GET_TOOTH_CLEAN_SUCCESS`;

export const GET_TOOTH_CLEAN_FAIL = `${NHI_INDEX_PAGE}GET_TOOTH_CLEAN_FAIL`;

export const GET_INDEX_TREATMENT_PRECEDURE = `${NHI_INDEX_PAGE}GET_INDEX_TREATMENT_PRECEDURE`;

export const GET_INDEX_TREATMENT_PRECEDURE_SUCCESS = `${NHI_INDEX_PAGE}GET_INDEX_TREATMENT_PRECEDURE_SUCCESS`;

export const GET_INDEX_TREATMENT_PRECEDURE_FAIL = `${NHI_INDEX_PAGE}GET_INDEX_TREATMENT_PRECEDURE_FAIL`;
