export const NHI_INDEX_PAGE = 'totoro-web-nhiIndexPage/';

export const INIT_NHI_SALARY = `${NHI_INDEX_PAGE}INIT_NHI_SALARY`;

export const GET_NHI_SALARY = `${NHI_INDEX_PAGE}GET_NHI_SALARY`;

export const GET_NHI_SALARY_SUCCESS = `${NHI_INDEX_PAGE}GET_NHI_SALARY_SUCCESS`;

export const NHI_SALARY_NOT_FOUND = `${NHI_INDEX_PAGE}NHI_SALARY_NOT_FOUND`;

export const GET_DOCTOR_NHI_SALARY = `${NHI_INDEX_PAGE}GET_DOCTOR_NHI_SALARY`;

export const GET_DOCTOR_NHI_SALARY_SUCCESS = `${NHI_INDEX_PAGE}GET_DOCTOR_NHI_SALARY_SUCCESS`;

export const GET_TOTAL_POINT_BY_DISPOSAL_DATE = `${NHI_INDEX_PAGE}GET_TOTAL_POINT_BY_DISPOSAL_DATE`;

export const GET_TOTAL_POINT_BY_DISPOSAL_DATE_SUCCESS = `${NHI_INDEX_PAGE}GET_TOTAL_POINT_BY_DISPOSAL_DATE_SUCCESS`;

export const GET_OD_INDEXES = `${NHI_INDEX_PAGE}GET_OD_INDEXES`;

export const GET_OD_INDEXES_SUCCESS = `${NHI_INDEX_PAGE}GET_OD_INDEXES_SUCCESS`;

export const GET_OD_INDEXES_FAIL = `${NHI_INDEX_PAGE}GET_OD_INDEXES_FAIL`;

export const GET_TOOTH_CLEAN = `${NHI_INDEX_PAGE}GET_TOOTH_CLEAN`;

export const GET_TOOTH_CLEAN_SUCCESS = `${NHI_INDEX_PAGE}GET_TOOTH_CLEAN_SUCCESS`;

export const GET_TOOTH_CLEAN_FAIL = `${NHI_INDEX_PAGE}GET_TOOTH_CLEAN_FAIL`;

export const GET_ENDO_INDEXES = `${NHI_INDEX_PAGE}GET_ENDO_INDEXES`;

export const GET_ENDO_INDEXES_SUCCESS = `${NHI_INDEX_PAGE}GET_ENDO_INDEXES_SUCCESS`;

export const GET_ENDO_INDEXES_FAIL = `${NHI_INDEX_PAGE}GET_ENDO_INDEXES_FAIL`;

export const GET_VALID_NHI_YEAR_MONTH = `${NHI_INDEX_PAGE}GET_VALID_NHI_YEAR_MONTH`;

export const GET_VALID_NHI_YEAR_MONTH_SUCCESS = `${NHI_INDEX_PAGE}GET_VALID_NHI_YEAR_MONTH_SUCCESS`;

export const VALID_NHI_YEAR_MONTH_NOT_FOUND = `${NHI_INDEX_PAGE}VALID_NHI_YEAR_MONTH_NOT_FOUND`;

export const GET_VALID_NHI_BY_YEAR_MONTH = `${NHI_INDEX_PAGE}GET_VALID_NHI_BY_YEAR_MONTH`;

export const GET_VALID_NHI_BY_YEAR_MONTH_SUCCESS = `${NHI_INDEX_PAGE}GET_VALID_NHI_BY_YEAR_MONTH_SUCCESS`;

export const VALID_NHI_BY_YEAR_MONTH_NOT_FOUND = `${NHI_INDEX_PAGE}VALID_NHI_BY_YEAR_MONTH_NOT_FOUND`;

export const GET_NHI_ONE_BY_DISPOSAL_ID = `${NHI_INDEX_PAGE}GET_NHI_ONE_BY_DISPOSAL_ID`;

export const GET_NHI_ONE_BY_DISPOSAL_ID_SUCCESS = `${NHI_INDEX_PAGE}GET_NHI_ONE_BY_DISPOSAL_ID_SUCCESS`;

export const NHI_ONE_BY_DISPOSAL_ID_NOT_FOUND = `${NHI_INDEX_PAGE}NHI_ONE_BY_DISPOSAL_ID_NOT_FOUND`;

export const ON_CHECKED_MODAL_DATA_CHANGE = `${NHI_INDEX_PAGE}ON_CHECKED_MODAL_DATA_CHANGE`;

export const INIT_CHECKED_MODAL_DATA_SUCCESS = `${NHI_INDEX_PAGE}INIT_CHECKED_MODAL_DATA_SUCCESS`;
