export const SHIFT_PAGE = 'totoro-web-shiftPage/';

export const CHANGE_DATE = `${SHIFT_PAGE}/CHANGE_DATE`;

export const GET_SHIFT_START = `${SHIFT_PAGE}/GET_SHIFT_START`;

export const GET_SHIFT_SUCCESS = `${SHIFT_PAGE}/GET_SHIFT_SUCCESS`;

export const CREATE_SHIFT_START = `${SHIFT_PAGE}/CREATE_SHIFT_START`;

export const CREATE_SHIFT_SUCCESS = `${SHIFT_PAGE}/CREATE_SHIFT_SUCCESS`;

export const GET_DEFAULT_SHIFT_START = `${SHIFT_PAGE}/GET_DEFAULT_SHIFT_START`;

export const GET_DEFAULT_SHIFT_SUCCESS = `${SHIFT_PAGE}/GET_DEFAULT_SHIFT_SUCCESS`;

export const EDIT_SHIFT_START = `${SHIFT_PAGE}/EDIT_SHIFT_START`;

export const EDIT_SHIFT_SUCCESS = `${SHIFT_PAGE}/EDIT_SHIFT_SUCCESS`;

export const CREATE_DEFAULT_SHIFT_TEMPLATE = `${SHIFT_PAGE}/CREATE_DEFAULT_SHIFT_TEMPLATE`;

export const CREATE_DEFAULT_SHIFT_START = `${SHIFT_PAGE}/CREATE_DEFAULT_SHIFT_START`;

export const CREATE_DEFAULT_SHIFT_SUCCESS = `${SHIFT_PAGE}/CREATE_DEFAULT_SHIFT_SUCCESS`;

export const DELETE_DEFAULT_SHIFT_START = `${SHIFT_PAGE}DELETE_DEFAULT_SHIFT_START`;

export const DELETE_DEFAULT_SHIFT_SUCCESS = `${SHIFT_PAGE}DELETE_DEFAULT_SHIFT_SUCCESS`;

export const CHANGE_DEFAULT_SHIFT_NAME = `${SHIFT_PAGE}/CHANGE_DEFAULT_SHIFT_NAME`;

export const CHANGE_DEFAULT_SHIFT_RANGE = `${SHIFT_PAGE}/CHANGE_DEFAULT_SHIFT_RANGE`;

export const SHIFT_DROP_START = `${SHIFT_PAGE}/SHIFT_DROP_START`;

export const SHIFT_DROP_SUCCESS = `${SHIFT_PAGE}/SHIFT_DROP_SUCCESS`;

export const GET_RESOURCE_COLOR_START = `${SHIFT_PAGE}/GET_RESOURCE_COLOR_START`;

export const GET_RESOURCE_COLOR_SUCCESS = `${SHIFT_PAGE}/GET_RESOURCE_COLOR_SUCCESS`;

export const CHANGE_RESOURCE_COLOR_START = `${SHIFT_PAGE}/CHANGE_RESOURCE_COLOR_START`;

export const CHANGE_RESOURCE_COLOR_SUCCESS = `${SHIFT_PAGE}/CHANGE_RESOURCE_COLOR_SUCCESS`;
