export const SHIFT_PAGE = 'totoro-web-shiftPage/';

export const CHANGE_DATE = `${SHIFT_PAGE}/CHANGE_DATE`;

export const GET_SHIFT_START = `${SHIFT_PAGE}/GET_SHIFT_START`;

export const GET_SHIFT_SUCCESS = `${SHIFT_PAGE}/GET_SHIFT_SUCCESS`;

export const CREATE_SHIFT_START = `${SHIFT_PAGE}/CREATE_SHIFT_START`;

export const CREATE_SHIFT_SUCCESS = `${SHIFT_PAGE}/CREATE_SHIFT_SUCCESS`;

export const EDIT_SHIFT_START = `${SHIFT_PAGE}/EDIT_SHIFT_START`;

export const EDIT_SHIFT_SUCCESS = `${SHIFT_PAGE}/EDIT_SHIFT_SUCCESS`;
