export const SETTING_PAGE = 'totoro-web-settingpage/';

export const GET_CONFIG_START = `${SETTING_PAGE}GET_CONFIG_START`;

export const GET_CONFIG_SUCCESS = `${SETTING_PAGE}GET_CONFIG_SUCCESS`;

export const SET_XRAY_VENDOR = `${SETTING_PAGE}SET_XRAY_VENDOR`;

export const SET_XRAY_VENDOR_SUCCESS = `${SETTING_PAGE}SET_XRAY_VENDOR_SUCCESS`;

export const ON_LEAVE_PAGE = `${SETTING_PAGE}ON_LEAVE_PAGE`;
