name: Download-Latest-Object
description: "Download latest object from google storage at specified path"
inputs:
  bucketName:  
    required: true
    default: totoro-admin-build
  path:
    description: "path for gsutil to get object with path"
    required: true
  hisGcpProjectId:
    required: true
  hisGcpServiceKey:
    required: true
runs:
  using: "composite"
  steps:
    - name: "Set up Cloud SDK"
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ inputs.hisGcpProjectId }}
        service_account_key: ${{ inputs.hisGcpServiceKey }}
        export_default_credentials: true
    - run: gsutil ls -l gs://${{ inputs.bucketName }}/${{ inputs.path }} | sed '$d' | tail -n 1 | awk '{ print $3 }' | xargs -I {} gsutil cp {} .
    - run: ls