const PATIENT_PAGE = 'totoro-web-patientPage/';

export const patientSearchMode = {
  name: 'name',
  phone: 'phone',
  birth: 'birth',
  medical_id: 'medical_id',
  national_id: 'national_id',
};

export const CHANGE_DRAWER_VISIBLE = `${PATIENT_PAGE}CHANGE_DRAWER_VISIBLE`;

export const CHANGE_DIAGNOSIS_NOTE_FOCUSED = `${PATIENT_PAGE}CHANGE_DIAGNOSIS_NOTE_FOCUSED`;

export const INIT_PATIENT_DETAIL = `${PATIENT_PAGE}INIT_PATIENT_DETAIL`;

export const PATIENT_NOT_FOUND = `${PATIENT_PAGE}PATIENT_NOT_FOUND`;

export const GET_PATIENT_SUCCESS = `${PATIENT_PAGE}GET_PATIENT_SUCCESS`;

export const GET_DISPOSAL = `${PATIENT_PAGE}GET_DISPOSAL`;

export const GET_DISPOSAL_SUCCESS = `${PATIENT_PAGE}GET_DISPOSAL_SUCCESS`;

export const GET_RECENT_TREATMENT_PROCEDURE = `${PATIENT_PAGE}GET_RECENT_TREATMENT_PROCEDURE`;

export const GET_RECENT_TREATMENT_PROCEDURE_SUCCESS = `${PATIENT_PAGE}GET_RECENT_TREATMENT_PROCEDURE_SUCCESS`;

export const GET_ACCUMULATED_MEDICAL_RECORD = `${PATIENT_PAGE}GET_ACCUMULATED_MEDICAL_RECORD`;

export const GET_ACCUMULATED_MEDICAL_RECORD_SUCCESS = `${PATIENT_PAGE}GET_ACCUMULATED_MEDICAL_RECORD_SUCCESS`;

export const GET_NHI_EXTEND_PATIENT = `${PATIENT_PAGE}GET_NHI_EXTEND_PATIENT`;

export const GET_NHI_EXTEND_PATIENT_SUCCESS = `${PATIENT_PAGE}GET_NHI_EXTEND_PATIENT_SUCCESS`;

export const GET_APPOINTMENT = `${PATIENT_PAGE}GET_APPOINTMENT`;

export const GET_APPOINTMENT_SUCCESS = `${PATIENT_PAGE}GET_APPOINTMENT_SUCCESS`;

export const GET_DOC_NP_HISTORY = `${PATIENT_PAGE}GET_DOC_NP_HISTORY`;

export const GET_DOC_NP_HISTORY_SUCCESS = `${PATIENT_PAGE}GET_DOC_NP_HISTORY_SUCCESS`;

export const GET_REGISTRATION_TODAY = `${PATIENT_PAGE}GET_REGISTRATION_TODAY`;

export const GET_REGISTRATION_TODAY_SUCCESS = `${PATIENT_PAGE}GET_REGISTRATION_TODAY_SUCCESS`;

export const ON_LEAVE_PAGE = `${PATIENT_PAGE}ON_LEAVE_PAGE`;

export const ADD_DATE_TO_CLINIC_NOTE = `${PATIENT_PAGE}ADD_DATE_TO_CLINIC_NOTE`;

export const CHANGE_CLINIC_NOTE = `${PATIENT_PAGE}CHANGE_CLINIC_NOTE`;

export const UPDATE_CLINIC_NOTE = `${PATIENT_PAGE}UPDATE_CLINIC_NOTE`;

export const UPDATE_CLINIC_NOTE_SUCCESS = `${PATIENT_PAGE}UPDATE_CLINIC_NOTE_SUCCESS`;

export const RESTORE_CLINIC_NOTE = `${PATIENT_PAGE}RESTORE_CLINIC_NOTE`;

// appointment list modal
export const CHANGE_APPOINTMENT_LIST_MODAL_VISIBLE = `${PATIENT_PAGE}CHANGE_APPOINTMENT_LIST_MODAL_VISIBLE`;

// search patient drawer
export const SEARCH_PATIENTS_START = `${PATIENT_PAGE}SEARCH_PATIENTS_START`;

export const SEARCH_PATIENT_SUCCESS = `${PATIENT_PAGE}SEARCH_PATIENT_SUCCESS`;

// treatment list modal
export const CHANGE_TREATMENT_LIST_MODAL_VISIBLE = `${PATIENT_PAGE}CHANGE_TREATMENT_LIST_MODAL_VISIBLE`;
