const QUESTIONNAIRE_PAGE = 'totoro-web-questionnairePage/';

export const NEXT_PAGE = `${QUESTIONNAIRE_PAGE}NEXT_PAGE`;

export const NEXT_PAGE_DELAY = `${QUESTIONNAIRE_PAGE}NEXT_PAGE_DELAY`;

export const PREV_PAGE = `${QUESTIONNAIRE_PAGE}PREV_PAGE`;

export const PREV_PAGE_DELAY = `${QUESTIONNAIRE_PAGE}PREV_PAGE_DELAY`;

export const GOTO_PAGE = `${QUESTIONNAIRE_PAGE}GOTO_PAGE`;

export const GOTO_PAGE_DELAY = `${QUESTIONNAIRE_PAGE}GOTO_PAGE_DELAY`;

export const PRE_CHANGE_GENDER = `${QUESTIONNAIRE_PAGE}PRE_CHANGE_GENDER`;

export const CHANGE_GENDER = `${QUESTIONNAIRE_PAGE}CHANGE_GENDER`;

export const PRE_CHANGE_BLOOD_TYPE = `${QUESTIONNAIRE_PAGE}PRE_CHANGE_BLOOD_TYPE`;

export const CHANGE_BLOOD_TYPE = `${QUESTIONNAIRE_PAGE}CHANGE_BLOOD_TYPE`;

export const PRE_CHANGE_CAREER = `${QUESTIONNAIRE_PAGE}PRE_CHANGE_CAREER`;

export const CHANGE_CAREER = `${QUESTIONNAIRE_PAGE}CHANGE_CAREER`;

export const PRE_CHANGE_MARRIAGE = `${QUESTIONNAIRE_PAGE}PRE_CHANGE_MARRIAGE`;

export const CHANGE_MARRIAGE = `${QUESTIONNAIRE_PAGE}CHANGE_MARRIAGE`;

export const PRE_CHANGE_EMERGENCY_RELATIONSHIP = `${QUESTIONNAIRE_PAGE}PRE_CHANGE_EMERGENCY_RELATIONSHIP`;

export const CHANGE_EMERGENCY_RELATIONSHIP = `${QUESTIONNAIRE_PAGE}CHANGE_EMERGENCY_RELATIONSHIP`;

export const CHANGE_DISEASE = `${QUESTIONNAIRE_PAGE}CHANGE_DISEASE`;

export const CHANGE_ALLERGY = `${QUESTIONNAIRE_PAGE}CHANGE_ALLERGY`;

export const PRE_CHANGE_DO_DRUG = `${QUESTIONNAIRE_PAGE}PRE_CHANGE_DO_DRUG`;

export const CHANGE_DO_DRUG = `${QUESTIONNAIRE_PAGE}CHANGE_DO_DRUG`;

export const PRE_CHANGE_PREGANT = `${QUESTIONNAIRE_PAGE}PRE_CHANGE_PREGANT`;

export const CHANGE_PREGANT = `${QUESTIONNAIRE_PAGE}CHANGE_PREGANT`;

export const PRE_CHANGE_SMOKING = `${QUESTIONNAIRE_PAGE}PRE_CHANGE_SMOKING`;

export const CHANGE_SMOKING = `${QUESTIONNAIRE_PAGE}CHANGE_SMOKING`;

export const CHANGE_OTHER = `${QUESTIONNAIRE_PAGE}CHANGE_OTHER`;

export const CHANGE_NAME = `${QUESTIONNAIRE_PAGE}CHANGE_NAME`;

export const CHANGE_BIRTH = `${QUESTIONNAIRE_PAGE}CHANGE_BIRTH`;

export const CHANGE_NATIONAL_ID = `${QUESTIONNAIRE_PAGE}CHANGE_NATIONAL_ID`;

export const CHANGE_PHONE = `${QUESTIONNAIRE_PAGE}CHANGE_PHONE`;

export const CHANGE_ADDRESS = `${QUESTIONNAIRE_PAGE}CHANGE_ADDRESS`;

export const CHANGE_INTRODUCER = `${QUESTIONNAIRE_PAGE}CHANGE_INTRODUCER`;

export const CHANGE_EMERGENCY_NAME = `${QUESTIONNAIRE_PAGE}CHANGE_EMERGENCY_NAME`;

export const CHANGE_EMERGENCY_PHONE = `${QUESTIONNAIRE_PAGE}CHANGE_EMERGENCY_PHONE`;

export const CHANGE_DRUG_A = `${QUESTIONNAIRE_PAGE}CHANGE_DRUG_A`;

export const CHANGE_PREGANT_A = `${QUESTIONNAIRE_PAGE}CHANGE_PREGANT_A`;

export const CHANGE_SMOKING_A = `${QUESTIONNAIRE_PAGE}CHANGE_SMOKING_A`;

export const CHANGE_IS_SIG_EMPTY = `${QUESTIONNAIRE_PAGE}CHANGE_IS_SIG_EMPTY`;

export const INIT_QUESTIONNAIRE = `${QUESTIONNAIRE_PAGE}INIT_QUESTIONNAIRE`;

export const CREATE_Q_WITH_SIGN = `${QUESTIONNAIRE_PAGE}CREATE_Q_WITH_SIGN`;

export const CREATE_Q_WITHOUT_SIGN = `${QUESTIONNAIRE_PAGE}CREATE_Q_WITHOUT_SIGN`;

export const CREATE_Q_SUCCESS = `${QUESTIONNAIRE_PAGE}CREATE_Q_SUCCESS`;

export const GET_PATIENT_START = `${QUESTIONNAIRE_PAGE}GET_PATIENT_START`;

export const GET_PATIENT_SUCCESS = `${QUESTIONNAIRE_PAGE}GET_PATIENT_SUCCESS`;

export const INIT_PAGE = `${QUESTIONNAIRE_PAGE}INIT_PAGE`;

export const GET_DOC_START = `${QUESTIONNAIRE_PAGE}GET_DOC_START`;

export const GET_DOC_SUCCESS = `${QUESTIONNAIRE_PAGE}GET_DOC_SUCCESS`;

export const VALIDATE_SUCCESS = `${QUESTIONNAIRE_PAGE}VALIDATE_SUCCESS`;

export const VALIDATE_FAIL = `${QUESTIONNAIRE_PAGE}VALIDATE_FAIL`;
