export const LOGIN_PAGE = 'totoro-web-loginPage/';

export const LOGIN_START = `${LOGIN_PAGE}LOGIN_START`;

export const LOGIN_SUCCESS = `${LOGIN_PAGE}SUCCESS`;

export const LOGIN_FAIL = `${LOGIN_PAGE}LOGIN_FAIL`;

export const CHANGE_LOGIN_SUCCESS = `${LOGIN_PAGE}CHANGE_LOGIN_SUCCESS`;

export const CHECK_TOKEN_VALIDATION = `${LOGIN_PAGE}CHECK_TOKEN_VALIDATION`;

export const CHECK_TOKEN_VALIDATION_FAIL = `${LOGIN_PAGE}CHECK_TOKEN_VALIDATION_FAIL`;
