name: "Init milestone"

on:
    workflow_call:
        inputs:
            content:
                required: true
                type: string
            currentMilestone:
                required: true
                type: string
            dependedMilestone:
                required: true
                type: string
        secrets:
            hisGcpProjectId:
                required: true
            hisGcpServiceKey:
                required: true
            totoroVersionAccessToken:
                required: true

jobs:
    # Create-Milestone-History:
    #     runs-on: ubuntu-18.04
    #     steps:
    #         - name: "Check out totoro version"
    #           uses: actions/checkout@v2
    #           with:
    #             repository: 'dentallio/totoro-version'
    #             ref: master
    #             token: ${{ secrets.totoroVersionAccessToken }}
    #             path: totoro-version
    #         - name: "check files"
    #           run: ls

    Check-Current-Milestone-Server-Init:
        runs-on: ubuntu-18.04
        steps:
            - name: "Check current milestone server folder on google storage"
              run: |
                if [[ ${#$(gsutil ls -l gs://totoro-admin-build/${{ inputs.currentMilestone }}/server)} -eq 0 ]]
                then
                    echo doCopyServer=true >> $GITHUB_ENV
                else
                    echo doCopyServer=false >> $GITHUB_ENV
                fi

    Copy-Latest-Server-From-Depended-Mileston-To-Google-Storage:
        runs-on: ubuntu-18.04
        needs: [ Check-Current-Milestone-Server-Init ]
        steps:
            - name: "Test"
              needs: [ Check-Current-Milestone-Server-Init ]
              if: ${{ env.doCopyServer }}
              run:
                echo do copy
            # - name: "Download latest web zip of current milestone from google storage"
            #   if: ${{ env.existServer }}
            #   run: |
            #   gsutil ls -l gs://totoro-admin-build/${{ inputs.dependedMilestone }}/server | \
            #   sed '$d' | \
            #   tail -n 1 | \
            #   awk '{ printf ${{ inputs.currentMilestone }}, " ", ${{ inputs.dependedMilestone }} }' | \
            #   xargs -I {} gsutil cp {}

    # Copy-Latest-Web-From-Depended-Mileston-To-Google-Storage:
    #     runs-on: ubuntu-18.04
    #     steps:
    #         - name: "Download latest web zip of current milestone from google storage"
    #           run: |
    #           gsutil ls -l gs://totoro-admin-build/${{ inputs.dependedMilestone }}/web | \
    #           sed '$d' | \
    #           tail -n 1 | \
    #           awk '{ printf ${{ inputs.currentMilestone }}, " ", ${{ inputs.dependedMilestone }} }' | \
    #           xargs -I {} gsutil cp {}
