name: "Init milestone"

on:
    workflow_call:
        inputs:
            milestone:
                required: true
                type: string
        secrets:
            hisGcpProjectId:
                required: true
            hisGcpServiceKey:
                required: true
            totoroVersionAccessToken:
                required: true

jobs:
    History-Checking:
        runs-on: ubuntu-18.04
        steps:
            - name: "Check out totoro version"
              uses: actions/checkout@v2
              with:
                repository: 'dentallio/totoro-version'
                ref: master
                token: ${{ secrets.totoroVersionAccessToken }}
                path: totoro-version
            - name: "check files"
              run: |
                ls totoro-version/${{ inputs.milestone }}.json

    History-Creation:
        runs-on: ubuntu-18.04
        needs: [ History-Checking ]
        if: ${{ failure() }}
        steps:
            - name: "Check out totoro version"
              uses: actions/checkout@v2
              with:
                repository: 'dentallio/totoro-version'
                ref: master
                token: ${{ secrets.totoroVersionAccessToken }}
                path: totoro-version
            - name: "Create empty json history"
              run: |
                cd totoro-version
                echo '{"history":[]}' > ${{ inputs.milestone }}.json
                git config --global user.email "github-auto@dentall.io"
                git config --global user.name "github-auto"
                git add .
                git commit -am "Create history file for ${{ inputs.milestone }}"
                git push

    Calculate-Previous-Milestone:
      runs-on: ubuntu-18.04
      outputs:
        dependedMilestone: ${{ steps.calculate.outputs.milestone }}
      steps:
        - id: calculate
          run: |
            echo ${{ github.ref_name }} | \
            awk '{ split($1, a, "-"); n=split(a[2], b, "."); printf "milestone-%s.%s", b[1], b[2]-1; }' | \
            xargs -I {} echo "::set-output name=milestone::{}"

    Server-Checking:
        runs-on: ubuntu-18.04
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
            - name: "Check current milestone server folder on google storage"
              run: |
                gsutil ls -l gs://totoro-admin-build/${{ inputs.milestone }}/server 

    Server-Copy:
        runs-on: ubuntu-18.04
        needs: [ Calculate-Previous-Milestone, Server-Checking ]
        if: ${{ failure() }}
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
            - name: "Copy server"
              run: |
                gsutil ls -l \
                gs://totoro-admin-build/${{ needs.Calculate-Previous-Milestone.outputs.dependedMilestone }}/server | \
                sed '$d' | \
                tail -n 1 | \
                awk '{ printf $3  }' | \
                xargs -I {} gsutil cp {} gs://totoro-admin-build/${{ inputs.milestone }}/server/

    Web-Checking:
        runs-on: ubuntu-18.04
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
            - name: "Check current milestone server folder on google storage"
              run: |
                gsutil ls -l gs://totoro-admin-build/${{ inputs.milestone }}/web 

    Web-Copy:
        runs-on: ubuntu-18.04
        needs: [ Calculate-Previous-Milestone, Web-Checking ]
        if: ${{ failure() }}
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
            - name: "Copy server"
              run: |
                gsutil ls -l \
                gs://totoro-admin-build/${{ needs.Calculate-Previous-Milestone.outputs.dependedMilestone }}/web | \
                sed '$d' | \
                tail -n 1 | \
                awk '{ printf $3  }' | \
                xargs -I {} gsutil cp {} gs://totoro-admin-build/${{ inputs.milestone }}/web/