name: "Init milestone"

on:
    workflow_call:
        inputs:
            content:
                required: true
                type: string
            currentMilestone:
                required: true
                type: string
            dependedMilestone:
                required: true
                type: string
        secrets:
            hisGcpProjectId:
                required: true
            hisGcpServiceKey:
                required: true

jobs:
    Create-Milestone-History:
        runs-on: ubuntu-18.04
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
            - name: "Notify to Slack"
              run: curl --location --request POST "${{ secrets.slackQaChannelHook }}" --header "Content-Type:application/json" --data-raw '{"text":"${{ inputs.content }}"}'

    Copy-Latest-Server-From-Depended-Mileston-To-Google-Storage:
        runs-on: ubuntu-18.04
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true

    Copy-Latest-Web-From-Depended-Mileston-To-Google-Storage:
        runs-on: ubuntu-18.04
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
