name: "Init milestone"

on:
    workflow_call:
        inputs:
            content:
                required: true
                type: string
            currentMilestone:
                required: true
                type: string
            dependedMilestone:
                required: true
                type: string
        secrets:
            hisGcpProjectId:
                required: true
            hisGcpServiceKey:
                required: true
            totoroVersionAccessToken:
                required: true

jobs:
    History-Checking:
        runs-on: ubuntu-18.04
        steps:
            - name: "Check out totoro version"
              uses: actions/checkout@v2
              with:
                repository: 'dentallio/totoro-version'
                ref: master
                token: ${{ secrets.totoroVersionAccessToken }}
                path: totoro-version
            - name: "check files"
              run: |
                ls totoro-version/${{ inputs.currentMilestone }}

    History-Creation:
        runs-on: ubuntu-18.04
        needs: [ History-Checking ]
        if: ${{ failure() }}
        steps:
            - name: "Check out totoro version"
              uses: actions/checkout@v2
              with:
                repository: 'dentallio/totoro-version'
                ref: master
                token: ${{ secrets.totoroVersionAccessToken }}
                path: totoro-version
            - name: "Create empty json history"
              run: |
                echo '{}' > totoro-version/${{ inputs.currentMilestone }}.json

    Server-Checking:
        runs-on: ubuntu-18.04
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
            - name: "Check current milestone server folder on google storage"
              run: |
                gsutil ls -l gs://totoro-admin-build/${{ inputs.currentMilestone }}/server 

    Server-Copy:
        runs-on: ubuntu-18.04
        needs: [ Server-Checking ]
        if: ${{ failure() }}
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
            - name: "Copy server"
              run: |
                gsutil ls -l \
                gs://totoro-admin-build/${{ inputs.dependedMilestone }}/server | \
                sed '$d' | \
                tail -n 1 | \
                awk '{ printf $3  }' | \
                xargs -I {} gsutil cp {} gs://totoro-admin-build/${{ inputs.currentMilestone }}/server/
