name: "Init milestone"

on:
    workflow_call:
        inputs:
            content:
                required: true
                type: string
            currentMilestone:
                required: true
                type: string
            dependedMilestone:
                required: true
                type: string
        secrets:
            hisGcpProjectId:
                required: true
            hisGcpServiceKey:
                required: true
            totoroVersionAccessToken:
                required: true

jobs:
    Check-Milestone-History:
        runs-on: ubuntu-18.04
        steps:
            - name: "Check out totoro version"
              uses: actions/checkout@v2
              with:
                repository: 'dentallio/totoro-version'
                ref: master
                token: ${{ secrets.totoroVersionAccessToken }}
                path: totoro-version
            - name: "check files"
              run: |
                ls totoro-version/${{ inputs.currentMilestone }}

    Create-Milestone-History:
        runs-on: ubuntu-18.04
        needs: [ Check-Milestone-History ]
        if: ${{ failure() }}
        steps:
            - name: "Do"
              run: echo OK!

    Check-Milestone-Server-Init:
        runs-on: ubuntu-18.04
        steps:
            - name: "Set up Cloud SDK"
              uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.hisGcpProjectId }}
                  service_account_key: ${{ secrets.hisGcpServiceKey }}
                  export_default_credentials: true
            - name: "Check current milestone server folder on google storage"
              run: |
                gsutil ls -l gs://totoro-admin-build/${{ inputs.currentMilestone }}/server 

    Copy-Server:
        runs-on: ubuntu-18.04
        needs: [ Check-Milestone-Server-Init ]
        if: ${{ failure() }}
        steps:
            - name: "Correct branch"
              run: echo OK!
            # - name: "Set up Cloud SDK"
            #   uses: google-github-actions/setup-gcloud@master
            #   with:
            #       project_id: ${{ secrets.hisGcpProjectId }}
            #       service_account_key: ${{ secrets.hisGcpServiceKey }}
            #       export_default_credentials: true
            # - name: "Download latest web zip of current milestone from google storage"
            #   if: ${{ env.existServer }}
            #   run: |
            #     gsutil ls -l gs://totoro-admin-build/${{ inputs.dependedMilestone }}/server | \
            #     sed '$d' | \
            #     tail -n 1 | \
            #     awk '{ printf ${{ inputs.dependedMilestone }}, " ", ${{ inputs.currentMilestone }} }' | \
            #     xargs -I {} gsutil cp {}
