name: "Init milestone"

on:
    workflow_call:
        inputs:
            content:
                required: true
                type: string
            currentMilestone:
                required: true
                type: string
            dependedMilestone:
                required: true
                type: string
        secrets:
            hisGcpProjectId:
                required: true
            hisGcpServiceKey:
                required: true

jobs:
    Create-Milestone-History:
        runs-on: ubuntu-18.04
        steps:
            - name: "Check out totoro version"
              uses: actions/checkout@v2
              with:
                repository: 'totoro-version'
                ref: master
                token: ${{ secrets.TOTORO_VERSION_ACCESS }}
                path: totoro-version
            - name: "check files"
              run: ls

    Copy-Latest-Server-From-Depended-Mileston-To-Google-Storage:
        runs-on: ubuntu-18.04
        steps:
            - name: "Just echo"
              run: echo copy server

    Copy-Latest-Web-From-Depended-Mileston-To-Google-Storage:
        runs-on: ubuntu-18.04
        steps:
            - name: "Just echo"
              run: echo copy web
