# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: NHI Rule Integration Test

on:
    workflow_dispatch:
    push:
        branches:
            - '**nhi-rule**'
    pull_request:
        branches:
            - '**nhi-rule**'

jobs:
    Nhi-Rule-Test-Part1:
        runs-on: [ self-hosted, dentall-his-runner ]
        steps:
            -   name: "Check out branch"
                uses: actions/checkout@v2
            -   name: "Set up JDK 1.8"
                uses: actions/setup-java@v2
                with:
                    java-version: '8'
                    distribution: 'adopt-openj9'
            -   name: "Grant execute permission for gradlew"
                run: chmod +x gradlew
            -   name: "Run NHI Rule Integration Test Automatic"
                run: ./gradlew cucumber_nhi_rule_1
            -   name: "Upload Cucumber Report"
                if: ${{ failure() }}
                uses: actions/upload-artifact@v2.2.4
                with:
                    name: cucumber-artifact-1
                    path: build/reports/cucumber1/

    Nhi-Rule-Test-Part2:
        runs-on: [ self-hosted, dentall-his-runner-2 ]
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_DB: totoro
                    POSTGRES_USER: totoro
                    POSTGRES_PASSWORD: totoro
        steps:
            -   name: "Check out branch"
                uses: actions/checkout@v2
            -   name: "Set up JDK 1.8"
                uses: actions/setup-java@v2
                with:
                    java-version: '8'
                    distribution: 'adopt-openj9'
            -   name: "Run NHI Rule Integration Test Automatic"
                run: ./gradlew.bat --debug cucumber_nhi_rule_2
            -   name: "Upload Cucumber Report"
                if: ${{ failure() }}
                uses: actions/upload-artifact@v2.2.4
                with:
                    name: cucumber-artifact-2
                    path: build/reports/cucumber2/
