# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: NHI Rule Integration Test

on:
    workflow_dispatch:
    push:
        branches:
            - '**nhi-rule**'
    pull_request:
        branches:
            - '**nhi-rule**'

jobs:
    Nhi-Rule-Test:
        runs-on: [ self-hosted, dentall-his-runner ]
        strategy:
            matrix:
                tag: [ "@nhi-34-series", "@nhi-8-series", "@nhi-89-series", "@nhi-90-series", "@nhi-91-series", "@nhi-92-series", "@nhi and (not @nhi-34-series and not @nhi-8-series and not @nhi-89-series and not @nhi-90-series and not @nhi-91-series and not @nhi-92-series)" ]
        steps:
            -   name: "Check out branch"
                uses: actions/checkout@v2
            -   name: "Set up JDK 1.8"
                uses: actions/setup-java@v2
                with:
                    java-version: '8'
                    distribution: 'adopt-openj9'
            -   name: "Grant execute permission for gradlew"
                if: ${{ runner.os == 'Linux' }}
                run: chmod +x gradlew
                shell: bash
            -   name: "Run NHI Rule Integration Test Automatic on Linux"
                if: ${{ runner.os == 'Linux' }}
                run: ./gradlew -Pcucumber.filter.tags="${{ matrix.tag }}" cucumber_nhi_rule
                shell: bash
            -   name: "Run NHI Rule Integration Test Automatic on Windows"
                if: ${{ runner.os == 'Windows' }}
                run: ./gradlew.bat -P cucumber.filter.tags="${{ matrix.tag }}" cucumber_nhi_rule
            -   name: "Upload Cucumber Report"
                if: ${{ failure() }}
                uses: actions/upload-artifact@v2.2.4
                with:
                    name: nhirule-artifact-${{ hashFiles('build/reports/nhirule/cucumber.html') }}
                    path: build/reports/nhirule/
