name: "Push to dev"

on:
    push:
        tags:
            - 'milestone-*-*'
jobs:
#    Run-Test:
#        uses: dentallio/totoro-admin/.github/workflows/run-test.yml@new-cicd

    Props:
        runs-on: ubuntu-18.04
        if: ${{ startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/') }}
        outputs:
            tag-name: ${{ steps.setup-props-value.outputs.tag-name }}
            tag-timestamp: ${{ steps.setup-props-value.outputs.tag-timestamp }}
            war-name: ${{ steps.setup-props-value.outputs.war-name }}
            version-file: ${{ steps.setup-props-value.outputs.version-file }}
            deploy-port: ${{ steps.setup-props-value.outputs.deploy-port }}
            notify: ${{ steps.setup-props-value.outputs.notify }}
            dev-deploy: ${{ steps.setup-props-value.outputs.dev-deploy }}
            gcp-release: ${{ steps.setup-props-value.outputs.gcp-release }}
            firebase-release: ${{ steps.setup-props-value.outputs.firebase-release }}
            run-nhi-rule-test: ${{ steps.setup-props-value.outputs.run-nhi-rule-test }}
            milestone: ${{ steps.setup-props-value.outputs.milestone }}
        steps:
            -   name: "Check out totoro admin"
                uses: actions/checkout@v2
            -   name: "Setup Props Value"
                id: setup-props-value
                run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/setup-props-value.sh
                shell: bash
                env:
                    GITHUB_REF: ${{ github.ref }}
                    GITHUB_SHA: ${{ github.sha }}

    Build-War:
        runs-on: ubuntu-18.04
        container: openjdk:8-jdk-stretch
        needs: [ Props ]
        if: ${{ startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/') }}
        env:
            WAR_NAME: ${{ needs.Props.outputs.war-name }}
            TAG_NAME: ${{ needs.Props.outputs.tag-name }}
            VERSION_FILE: ${{ needs.Props.outputs.version-file }}
        steps:
            -   name: "Install Tool"
                run: |
                    apt-get update -y && apt-get install jq curl unzip git -y
                    apt-get update && apt-get install -y --no-install-recommends --allow-unauthenticated gcc make libpng-dev
            -   name: "Check out totoro admin"
                uses: actions/checkout@v1
            -   name: "Check out totoro version"
                uses: actions/checkout@v2
                with:
                    repository: ${{ env.VERSION_REPOSITORY }}
                    ref: master
                    token: ${{ secrets.TOTORO_VERSION_ACCESS }}
                    path: totoro-version
            -   name: "Download web artifact"
                id: download-web-artifact
                run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/retrieve-web-artifact.sh
                shell: bash
                env:
                    TOKEN: ${{ secrets.TOTORO_VERSION_ACCESS }}
                    WEB_REPOSITORY: ${{ env.WEB_REPOSITORY }}
                    VERSION_FILE: ${{ env.VERSION_FILE }}
                working-directory: ./totoro-version
            -   uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-
            -   name: "Grant execute permission for gradlew"
                run: chmod +x gradlew
            -   name: "Build"
                run: |
                    ./gradlew bootWar -Pprod -x check --no-daemon
                    ls ${GITHUB_WORKSPACE}/build/libs/
            -   name: "Change war name By develop"
                if: ${{ startsWith(env.TAG_NAME, 'dev') }}
                run: ls totoro*.war | xargs -I {} mv {} ${WAR_NAME}
                env:
                    WAR_NAME: ${{ env.WAR_NAME }}
                working-directory: ./build/libs/
            -   name: "Upload his war"
                uses: actions/upload-artifact@v2
                with:
                    name: ${{ env.ARTIFACT_NAME }}
                    path: build/libs/${{ env.WAR_NAME }}

    Upload-War-To-Google-Storage:
        runs-on: ubuntu-18.04
        needs: [ Build-War, Props ]
        steps:
            -   name: "Set up Cloud SDK"
                uses: google-github-actions/setup-gcloud@master
                with:
                    project_id: ${{ secrets.hisGcpProjectId }}
                    service_account_key: ${{ secrets.hisGcpServiceKey }}
                    export_default_credentials: true
            -   name: "Download artifact war"
                uses: actions/download-artifact@v2
                with:
                    name: ${{ env.ARTIFACT_NAME }}
            -   name: "Upload war to google storage"
                run: gsutil cp ./${{ env.ARTIFACT_NAME }} gs://totoro-admin-build/${{ needs.Props.outputs.milestone }}/server/${{ github.ref_name }}.war

    Combine:
        needs: [ Upload-War-To-Google-Storage, Props ]
        uses: dentallio/totoro-version/.github/workflows/combine-web-and-server.yml@master
        with:
            milestone: ${{ needs.Props.outputs.mileston }}
            hisGcpRegistry: totoro-admin-dev
        secrets:
            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}
            totoroVersionAccessToken: ${{ secrets.TOTORO_VERSION_ACCESS }}

    Upload-Final:
        needs: [ Combine ]
        uses: dentallio/totoro-version/.github/workflows/copy-file-to-remote-machine.yml@master
        with:
            remoteHost: dev.dentall.site
            remoteUser: dentallio
            remotePath: /home/dentallio
            googleStoragePath: totoro-admin-build/${{ needs.Props.outputs.milestone }}/final/
            googleStorageFileName: ${{ needs.Combine.outputs.name }}
        secrets:
            remoteMachineToken: ${{ secrets.HIS_LOCAL_DEV_MACHINE_KEY }}
            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}

    Notify:
        needs: [ Upload-Final ]
        uses: dentallio/totoro-version/.github/workflows/send-slack-notification.yml@master
        with:
            content: Done full new cicd
        secrets:
            slackQaChannelHook: ${{ secrets.SLACK_QA_CHANNEL_HOOK }}
