name: "Run war on dev machine"

on:
    workflow_call:
        inputs:
            url:
                required: true
                type: string
            sleepTime:
                required: true
                type: number
            warFileName:
                required: true
                type: string

jobs:
    Stop-Dev-Machine:
        runs-on: ubuntu-latest
        steps:
        - name: "Stop target port machine"
          run: |
            curl --location --request POST \
            ${{ inputs.url }} \
            --header "Content-Type:application/json" \
            --data-raw '{"operation": "stop"}'

    Pause-A-While:
        runs-on: ubuntu-18.04
        needs: [ Stop-Dev-Machine ]
        if: ${{ always() }}
        steps:
        - name: sleep
          run: sleep ${{ inputs.sleepTime }}

    Start-Dev-Machine:
        runs-on: ubuntu-latest
        needs: [ Stop-Dev-Machine, Pause-A-While ]
        steps:
        - name: "Start target port machine"
          run: |
            curl --location --request POST \
            ${{ inputs.url }} \
            --header "Content-Type:application/json" \
            --data-raw '{"warVersion":"${{ inputs.warFileName }}", "operation": "start"}'
