name: "Run war on dev machine"

on:
    workflow_call:
        inputs:
            url:
                required: true
                type: string
            sleepTime:
                required: true
                type: number
            warFileName:
                required: true
                type: string
        secrets:
            hisGcpProjectId:
                required: true
            hisGcpServiceKey:
                required: true
jobs:
    Stop-Dev-Machine:
        steps:
            - name: "Stop target port machine"
              run: |
                curl --location --request POST \
                ${{ inputs.url }} \
                --header "Content-Type:application/json" \
                --data-raw '{"operation": "stop"}'
    Pause-A-While:
        needs: [ Stop-Dev-Machine ]
        if: ${{ always() }}
        steps:
            - name: sleep
              run: sleep ${{ inputs.sleepTime }}
    Start-Dev-Machine:
        needs: [ Stop-Dev-Machine, Pause-A-While ]
        runs-on: ubuntu-18.04
        steps:
            - name: "Start target port machine"
              run: |
                curl --location --request POST \
                ${{ inputs.url }} \
                --header "Content-Type:application/json" \
                --data-raw '{"warVersion":"${{ inputs.warFileName }}, "operation": "start"}'
