name: "Send slack notification"

on:
    workflow_call:
        inputs:
            content:
                required: true
                type: string
        secrets:
            slackQaChannelHook:
                required: true

jobs:
    Send-Slack-Notification:
        runs-on: ubuntu-18.04
        steps:
            - name: "Notify to Slack"
              run: curl --location --request POST "${{ secrets.slackQaChannelHook }}" --header "Content-Type:application/json" --data-raw "${{ inputs.content }}"
