name: "Test workflow"

on:
    push:
        branches:
            - new-cicd
    pull_request:

jobs:
    STEP1:
        uses: totoro-admin/.github/workflows/combine-web-and-server.yml@main
        with:
            milestone: "milestone-1.32"
        secrets:
            HIS_GCP_PROJECT_ID: ${{ secrets.HIS_GCP_PROJECT_ID }}
            HIS_GCP_SERVICE_KEY: ${{ secrets.HIS_GCP_SERVICE_KEY }}
