name: "Test workflow"

on:
    push:
        branches:
            - new-cicd
    pull_request:

jobs:
    Echo:
        runs-on: ubuntu-18.04
        steps:
            -   run: echo a
#    STEP2:
#        uses: dentallio/totoro-version/.github/workflows/combine-web-and-server.yml@master
#        with:
#            milestone: "milestone-1.32"
#            hisGcpRegistry: totoro-admin-dev
#        secrets:
#            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
#            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}
#            totoroVersionAccessToken: ${{ secrets.TOTORO_VERSION_ACCESS }}
#    Test2:
#        needs: [ STEP2 ]
#        runs-on: ubuntu-18.04
#        steps:
#            - run: echo ${{ needs.STEP2.outputs.finalFileName }}
#    Test:
#        uses: dentallio/totoro-admin/.github/workflows/run-test.yml@new-cicd
#    STEP1:
#        uses: dentallio/totoro-version/.github/workflows/init-milestone.yml@master
#        with:
#            content: "test content"
#            currentMilestone: "milestone-1.32"
#            dependedMilestone: "milestone-1.32"
#        secrets:
#            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
#            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}
#            totoroVersionAccessToken: ${{ secrets.TOTORO_VERSION_ACCESS }}
#
#    STEP2:
#        needs: [ STEP1 ]
#        uses: dentallio/totoro-version/.github/workflows/combine-web-and-server.yml@master
#        with:
#            milestone: "milestone-1.32"
#            hisGcpRegistry: totoro-admin-dev
#        secrets:
#            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
#            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}
#            totoroVersionAccessToken: ${{ secrets.TOTORO_VERSION_ACCESS }}
#
#    STEP3:
#        needs: [ STEP2 ]
#        uses: dentallio/totoro-version/.github/workflows/copy-file-to-remote-machine.yml@master
#        with:
#            remoteHost: dev.dentall.site
#            remoteUser: dentallio
#            remotePath: /home/dentallio
#            googleStoragePath: totoro-admin-build/milestone-1.32/final/
#            googleStorageFileName: records.json
#        secrets:
#            remoteMachineToken: ${{ secrets.HIS_LOCAL_DEV_MACHINE_KEY }}
#            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
#            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}
#
#    STEP4:
#        needs: [ STEP3 ]
#        uses: dentallio/totoro-version/.github/workflows/send-slack-notification.yml@master
#        with:
#            content: Done full new cicd
#        secrets:
#            slackQaChannelHook: ${{ secrets.SLACK_QA_CHANNEL_HOOK }}
