name: "Test workflow"

on:
    push:
        branches:
            - new-cicd
    pull_request:

jobs:
#    STEP1:
#        uses: dentallio/totoro-version/.github/workflows/combine-web-and-server.yml@master
#        with:
#            milestone: "milestone-1.32"
#        secrets:
#            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
#            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}

#    STEP2:
#        needs: [ STEP1 ]
#        uses: dentallio/totoro-version/.github/workflows/send-slack-notification.yml@master
#        with:
#            content: Test reusable workflow complex content
#        secrets:
#            slackQaChannelHook: ${{ secrets.SLACK_QA_CHANNEL_HOOK }}

#    STEP3:
#        uses: dentallio/totoro-version/.github/workflows/send-slack-notification.yml@master
#        with:
#            content: Test reusable workflow complex content
#            url: "http://dev.dentall.site:8001/servers/8083/operation"
#            warFileName: ""
#        secrets:
#            slackQaChannelHook: ${{ secrets.SLACK_QA_CHANNEL_HOOK }}
#
    STEP4COPY:
        uses: dentallio/totoro-version/.github/workflows/init-milestone.yml@master
        with:
            content: "test content"
            currentMilestone: "milestone-1.31"
            dependedMilestone: "milestone-1.31"
        secrets:
            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}
            totoroVersionAccessToken: ${{ secrets.TOTORO_VERSION_ACCESS }}

    STEP4NoCOPY:
        uses: dentallio/totoro-version/.github/workflows/init-milestone.yml@master
        with:
            content: "test content"
            currentMilestone: "milestone-1.32"
            dependedMilestone: "milestone-1.31"
        secrets:
            hisGcpProjectId: ${{ secrets.HIS_GCP_PROJECT_ID }}
            hisGcpServiceKey: ${{ secrets.HIS_GCP_SERVICE_KEY }}
