export const SMS_PAGE = 'totoro-web-smsPage/';

export const GET_EVENTS = `${SMS_PAGE}GET_EVENTS`;
export const GET_EVENTS_SUCCESS = `${SMS_PAGE}GET_EVENTS_SUCCESS`;

export const SET_SELECT_EVENT = `${SMS_PAGE}SET_SELECT_EVENT`;

export const CREATE_EVENT = `${SMS_PAGE}CREATE_EVENT`;

export const EDIT_TITLE = `${SMS_PAGE}EDIT_TITLE`;
export const EDIT_TEMPLATE = `${SMS_PAGE}EDIT_TEMPLATE`;

export const FILTER_EVENTS = `${SMS_PAGE}FILTER_EVENTS`;
export const ADD_TAG = `${SMS_PAGE}ADD_TAG`;

export const SAVE_EVENT = `${SMS_PAGE}SAVE_EVENT`;
export const SAVE_EVENT_SUCCESS = `${SMS_PAGE}SAVE_EVENT_SUCCESS`;
export const EXECUTE_EVENT = `${SMS_PAGE}EXECUTE_EVENT`;
export const EXECUTE_EVENT_FAILED = `${SMS_PAGE}EXECUTE_EVENT_FAILED`;
export const DELETE_EVENT = `${SMS_PAGE}DELETE_EVENT`;
export const DELETE_EVENT_SUCCESS = `${SMS_PAGE}DELETE_EVENT_SUCCESS`;
export const SAVE_EVENT_AND_SEND_IMMEDIATELY = `${SMS_PAGE}SAVE_EVENT_AND_SEND_IMMEDIATELY`;



export const TOGGLE_APPOINTMENT_MODAL = `${SMS_PAGE}TOGGLE_APPOINTMENT_MODAL`;
export const GET_APPOINTMENTS = `${SMS_PAGE}GET_APPOINTMENTS`;
export const GET_APPOINTMENTS_SUCCESS = `${SMS_PAGE}GET_APPOINTMENTS_SUCCESS`;
export const ADD_CONTACT_APPOINTMENTS = `${SMS_PAGE}ADD_CONTACT_APPOINTMENTS`;
export const UNSELECT_APPOINTMENT = `${SMS_PAGE}UNSELECT_APPOINTMENT`;



export const TOGGLE_PREVIEWING_MODAL = `${SMS_PAGE}TOGGLE_PREVIEWING_MODAL`;

export const GET_CLINIC_SETTINGS = `${SMS_PAGE}GET_CLINIC_SETTINGS`;
export const GET_CLINIC_SETTINGS_SUCCESS = `${SMS_PAGE}GET_CLINIC_SETTINGS_SUCCESS`;


export const GET_CLINIC_REMAINING = `${SMS_PAGE}GET_CLINIC_REMAINING`;
export const GET_CLINIC_REMAINING_SUCCESS = `${SMS_PAGE}GET_CLINIC_REMAINING_SUCCESS`;
